# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmLQOjqSC7HGwtYyJo49dKnEY8bJyzia
"""

app_code = '''
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
import holidays

# Load model and data
model = joblib.load('rf_model.pkl')
features = joblib.load('features.pkl')
hourly_data = pd.read_csv('hourly_data.csv', index_col='Opened', parse_dates=True)

# Generate 7-day forecast
def generate_forecast(hourly_data):
    last_known = hourly_data.iloc[-168:].copy()
    last_timestamp = hourly_data.index[-1]
    future_index = pd.date_range(start=last_timestamp + pd.Timedelta(hours=1), periods=168, freq=\'h\')

    future_df = pd.DataFrame(index=future_index)
    future_df[\'hour\'] = future_df.index.hour
    future_df[\'day_of_week\'] = future_df.index.dayofweek
    future_df[\'is_weekend\'] = future_df[\'day_of_week\'].isin([5, 6]).astype(int)

    years = future_df.index.year.unique()
    us_holidays = holidays.US(years=years)
    future_df[\'is_holiday\'] = future_df.index.normalize().isin(us_holidays).astype(int)
    future_df[\'hour_sin\'] = np.sin(2 * np.pi * future_df[\'hour\'] / 24)
    future_df[\'hour_cos\'] = np.cos(2 * np.pi * future_df[\'hour\'] / 24)
    future_df[\'guests_lag168\'] = last_known[\'# of Guests\'].values
    future_df[\'guests_lag24\'] = hourly_data[\'# of Guests\'].iloc[-24:].tolist() * 7
    future_df[\'guests_lag1\'] = hourly_data[\'# of Guests\'].iloc[-168:].shift(1).fillna(0).tolist()
    future_df[\'guests_lag2\'] = hourly_data[\'# of Guests\'].iloc[-168:].shift(2).fillna(0).tolist()

    future_df[\'predicted_guests\'] = model.predict(future_df[features])
    future_df[\'predicted_guests\'] = future_df[\'predicted_guests\'].clip(lower=0).round(2)
    return future_df

forecast_df = generate_forecast(hourly_data)

# App layout
st.title("🍜 Customer Traffic Dashboard")
st.markdown("Select a date to view historical traffic or the 7-day forecast.")

# Date picker
all_dates = pd.concat([
    pd.Series(hourly_data.index.normalize().unique()),
    pd.Series(forecast_df.index.normalize().unique())
]).drop_duplicates().sort_values()

selected_date = st.date_input(
    "Select a date",
    value=forecast_df.index.normalize().unique()[0],
    min_value=all_dates.min(),
    max_value=all_dates.max()
)

selected_date = pd.Timestamp(selected_date)
is_forecast = selected_date in forecast_df.index.normalize()

# Get data for selected date
if is_forecast:
    day_data = forecast_df[forecast_df.index.normalize() == selected_date][\'predicted_guests\']
    label = "Predicted # of Guests"
    color = \'orange\'
    tag = "📅 Forecast"
else:
    day_data = hourly_data[hourly_data.index.normalize() == selected_date][\'# of Guests\']
    label = "Actual # of Guests"
    color = \'steelblue\'
    tag = "📋 Historical"

# Summary metrics
st.subheader(f"{tag} — {selected_date.strftime(\'%A, %B %d %Y\')}")
col1, col2, col3 = st.columns(3)
col1.metric("Total Guests", int(day_data.sum()))
col2.metric("Peak Hour", f"{day_data.idxmax().strftime(\'%I:%M %p\') if not day_data.empty and day_data.sum() > 0 else \'N/A\'}")
col3.metric("Avg Guests/Hour", round(day_data.mean(), 2))

# Bar chart
st.subheader("Hourly Traffic")
fig, ax = plt.subplots(figsize=(12, 4))
bars = ax.bar(day_data.index.hour, day_data.values, color=[
    \'green\' if v < 2 else \'orange\' if v < 4 else \'red\' for v in day_data.values
])
ax.set_xticks(range(24))
ax.set_xticklabels([f"{h}:00" for h in range(24)], rotation=45)
ax.set_ylabel(label)
ax.set_title(f"Hourly Traffic — {selected_date.strftime(\'%B %d, %Y\')}")
st.pyplot(fig)

# Weekly forecast overview
st.subheader("📊 7-Day Forecast Overview")
weekly = forecast_df.groupby(forecast_df.index.normalize())[\'predicted_guests\'].sum()
fig2, ax2 = plt.subplots(figsize=(10, 4))
ax2.bar(range(len(weekly)), weekly.values, color=\'orange\')
ax2.set_xticks(range(len(weekly)))
ax2.set_xticklabels([d.strftime(\'%a %b %d\') for d in weekly.index], rotation=30)
ax2.set_ylabel("Total Predicted Guests")
ax2.set_title("Total Predicted Guests per Day (Next 7 Days)")
st.pyplot(fig2)
'''

with open('app.py', 'w') as f:
    f.write(app_code)

print("app.py created!")

from google.colab import files
files.download('app.py')